import { TableColumn } from "src/app/shared/components/content/table/table.types";

export const COMPANY_GROUPING_COLUMNS: TableColumn[] = [
  { label: 'Sigla Empr', property: 'siglaEmpr', textAlignment: 'center' },
  { label: 'Descrição Empr', property: 'descricaoEmpr' },
  { label: 'Cód. Agrup.', property: 'codAgrup', textAlignment: 'center' },
  { label: 'Descrição Agrup.', property: 'descricaoAgrup' },
  { label: 'Tipo Prod', property: 'tipoProd', textAlignment: 'center' },
  { label: 'Descrição Prod', property: 'descricaoProd' },
  { label: 'Obj?', property: 'obj', textAlignment: 'center' },
  { label: 'Usuário', property: 'usuario' },
  { label: 'Data', property: 'data' }
];

export const COMPANY_GROUPING_DATA = [
  {
    siglaEmpr: 'ABC',
    descricaoEmpr: 'COMÉRCIO GERAL',
    codAgrup: 301,
    descricaoAgrup: 'ELETRODOMÉSTICOS GRANDES',
    tipoProd: 101,
    descricaoProd: 'LAVADORAS',
    obj: 'S',
    usuario: 'JOÃO LIMA',
    data: '01/11/2024',
  },
  {
    siglaEmpr: 'DEF',
    descricaoEmpr: '',
    codAgrup: 302,
    descricaoAgrup: 'ACESSÓRIOS DE INFORMÁTICA',
    tipoProd: 102,
    descricaoProd: 'TECLADOS',
    obj: 'N',
    usuario: 'MARIA EDUARDA',
    data: '02/11/2024',
  },
  {
    siglaEmpr: 'GHI',
    descricaoEmpr: 'INDÚSTRIA TECNOLÓGICA',
    codAgrup: 303,
    descricaoAgrup: 'MÓVEIS RÚSTICOS',
    tipoProd: 103,
    descricaoProd: 'CADEIRAS',
    obj: 'S',
    usuario: 'CARLOS HENRIQUE',
    data: '03/11/2024',
  },
  {
    siglaEmpr: 'JKL',
    descricaoEmpr: 'SERVIÇOS DE DECORAÇÃO',
    codAgrup: 304,
    descricaoAgrup: 'ITENS DE COZINHA',
    tipoProd: 104,
    descricaoProd: 'TALHERES',
    obj: 'N',
    usuario: 'ANA PAULA',
    data: '04/11/2024',
  },
  {
    siglaEmpr: 'MNO',
    descricaoEmpr: '',
    codAgrup: 305,
    descricaoAgrup: 'SAPATOS MASCULINOS',
    tipoProd: 105,
    descricaoProd: 'SOCIAIS',
    obj: 'S',
    usuario: 'FERNANDO COSTA',
    data: '05/11/2024',
  },
  {
    siglaEmpr: 'PQR',
    descricaoEmpr: 'PET SUPPLIES',
    codAgrup: 306,
    descricaoAgrup: 'ROUPAS PARA CÃES',
    tipoProd: 106,
    descricaoProd: 'CAMISETA',
    obj: 'N',
    usuario: 'LUCAS MARTINS',
    data: '06/11/2024',
  },
  {
    siglaEmpr: 'STU',
    descricaoEmpr: 'ATACADO DE JOGOS',
    codAgrup: 307,
    descricaoAgrup: 'JOGOS DE TABULEIRO',
    tipoProd: 107,
    descricaoProd: 'XADREZ',
    obj: 'S',
    usuario: 'PAULA OLIVEIRA',
    data: '07/11/2024',
  },
  {
    siglaEmpr: 'VWX',
    descricaoEmpr: '',
    codAgrup: 308,
    descricaoAgrup: 'FERRAMENTAS ELÉTRICAS',
    tipoProd: 108,
    descricaoProd: 'FURADEIRAS',
    obj: 'N',
    usuario: 'GABRIEL MOREIRA',
    data: '08/11/2024',
  },
  {
    siglaEmpr: 'YZA',
    descricaoEmpr: 'EXPORTAÇÃO DE JOGOS',
    codAgrup: 309,
    descricaoAgrup: 'PUZZLES',
    tipoProd: 109,
    descricaoProd: 'QUEBRA-CABEÇAS',
    obj: 'S',
    usuario: 'LUIZA SANTOS',
    data: '09/11/2024',
  },
  {
    siglaEmpr: 'BCD',
    descricaoEmpr: 'IMPORTAÇÃO PAPELARIA',
    codAgrup: 310,
    descricaoAgrup: 'BOLAS ESPORTIVAS',
    tipoProd: 110,
    descricaoProd: 'FUTEBOL',
    obj: 'N',
    usuario: 'RICARDO BARROS',
    data: '10/11/2024',
  },
];


